[package]
name = "example-2"
version = "0.1.0"
edition = "2024"

[dependencies]
function-compose = {version = "0.3.0", path = "../function-compose"}
futures = "0.3.29"
retry = "2.0.0"
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3.0"
